name: PlatformIO CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: PlatformIO Run
                uses: karniv00l/platformio-run-action@v1
                with:
                    environments: "uno"
                    targets: "uno"
                    jobs: 6
                    silent: false
                    verbose: true
                    disable-auto-clean: false
